### ISSUE TITLE
64-bit Excel not running c# code properly

### ISSUE THREAD

**Issue by shaddy43** [FortyNorthSecurity/EXCELntDonut#11]
So, i've tried to run a simple ransomware simulation using the ExcelntDonut framework. I've input a c# code which encrypts the given directory. Now, this code is running and executing properly on 32-bit Excel but not working on 64-bit Excel.

**Comment by joeleonjr** [comment]
Do you mind sharing a sample of the code? It's hard to debug without seeing the C# code. Thanks.

**Comment by f0cker** [comment]
I'm experiencing the same, x86 payload works fine but not x64. Basic calc.exe shellcode execution fails, I can share an example cs file if you want.

**Comment by shtry** [comment]
Exactly this tool doesn't work.

command line :  EXCELntDonut -f msg.cs -r System.Windows.Forms.dll -o test.bin
Sample file : 
[0116_1.zip](https://github.com/FortyNorthSecurity/EXCELntDonut/files/5821702/0116_1.zip)
(PW: 123456)

shell code:

[test.zip](https://github.com/FortyNorthSecurity/EXCELntDonut/files/5821722/test.zip)

**Comment by joeleonjr** [comment]
We're happy to review shellcode templates to see if we can figure out where it's going wrong. 64-bit is tricky with XLM macros. @shtry please copy/paste the C# file in a comment or put it on a gist. We're not going to download a zip file.

**Comment by ChrisTruncer** [comment]
@shtry - This tool has been tested and used by us, so we have verified that it does work otherwise it would have never been released. You’re talking to people who work on open source tools on their own free time, having a bad attitude in your post is a bad way to try to get any assistance especially when you’re being rude to the authors. If you would like support in the future, which we are happy to give, please be respectful or don’t post at all if you can’t.

**Comment by ChrisTruncer** [comment]
Closing this issue for now since we haven't heard back. If you want to provide your sample code (on a gist, pastebin, etc.), feel free to post a link here and we will review it.
